id: airflow-cfg

info:
  name:
  author: geeknik
  description: Apache Airflow is a platform to programmatically author, schedule and monitor workflows.
  reference: https://github.com/apache/airflow/blob/master/airflow/config_templates/default_airflow.cfg
  severity: low
  tags: config,apache,airflow

requests:
  - method: GET
    path:
      - "{{BaseURL}}/airflow.cfg"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "[core]"
          - "[logging]"
          - "[metrics]"
          - "[secrets]"
        condition: and
