id: cloud-config-leak

info:
  name: Cloud Config Leak
  author: atomiczsec
  severity: low
  reference:
    - https://www.exploit-db.com/ghdb/7959
  tags: config,exposure
requests:
  - method: GET
    path:
      - "{{BaseURL}}/cloud-config.yml"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "#cloud-config"

