id: docker-compose-config

info:
  name: docker-compose.yml exposure
  author: meme-lord & blckraven
  severity: medium

requests:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/docker-compose.yml"
    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'regex("^version: ", body) && contains(body, "services:") == true'

      - type: status
        status:
          - 200
