id: jetbrains-workspace

info:
  name: Jetbrains worspace exposure
  author: tess
  severity: info
  metadata:
    verified: true
    google-query: intitle:"index of" "WebServers.xml"
  tags: config,exposure,jetbrains

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.idea/workspace.xml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ChangeListManager"
        part: body

      - type: status
        status:
          - 200
