id: prometheus-flags-endpoint

info:
  name: Exposure of sensitive operational information via Prometheus flags API endpoint
  author: geeknik
  description: The flags endpoint provides a full path to the configuration file. If the file is stored in the home directory, it may leak a username.
  reference: https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  severity: medium
  tags: prometheus,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/status/config"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
        words:
          - '"data":'
          - '"config.file":'
        condition: and
