id: somansa-dlp-configuration-manager-login

info:
  name: Somansa DLP Configuration manager login
  author: lrtk,gy741
  severity: high
  description: |
    Somansa DLP Configuration manager default password login.
  reference:
    - https://www.somansa.com/solution/integrated_solution/dlp/
  metadata:
    verified: true
    shodan-query: http.html:"DLP system"
  tags: login,default_password,somansa,dlp

headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}/cm/index.do"

      - action: waitload

      - action: click
        args:
          by: xpath
          xpath: //*[@id="pwdPassword"]

      - action: waitload

      - action: text
        args:
          by: xpath
          xpath: //*[@id="pwdPassword"]
          value: "sms980502!"

      - action: waitload

      - action: click
        args:
          by: xpath
          xpath: //*[@id="btnLogin"]

      - action: waitload

    matchers:
      - type: word
        part: body
        words:
          - "Backup/Restore Process PopView"
          - "rdoSmtpAuthUse"
        condition: or
