id: phpsys-info

info:
  name: phpSysInfo Exposure
  author: fpatrik
  severity: low
  description: |
    phpSysInfo: a customizable PHP script that displays information about your system nicely
  reference: https://phpsysinfo.github.io/phpsysinfo/
  metadata:
    max-request: 1
    shodan-query: html:"phpSysInfo"
    verified: true
  tags: config,exposure,phpsysinfo

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpsysinfo/index.php?disp=bootstrap"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'phpSysInfo'
          - 'Hardware Information'
        condition: and

      - type: status
        status:
          - 200
