id: symfony-debug

info:
  name: Symfony Debug - Detect
  author: kazet
  severity: medium
  description: Symfony debug was detected - such configuration may expose sensitive information such as API keys.
  metadata:
    max-request: 3
    verified: true
  tags: config,exposure,symfony

http:
  - method: GET
    path:
      - "{{BaseURL}}/admin_dev.php"
      - "{{BaseURL}}/index_dev.php"
      - "{{BaseURL}}/app_dev.php"

    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - 'id="sfWebDebugSymfony"'
