id: tugboat-config-exposure
info:
  name: Tugboat Configuration File Exposure
  author: geeknik
  severity: critical
  description: The Tugboat Configuration File Exposure is the discovery of a Tugboat
    configuration file, which is a command line tool used for interacting with DigitalOcean
    droplets.
  reference:
  - https://github.com/petems/tugboat
  - https://www.digitalocean.com/community/tools/tugboat
  tags: tugboat,config,exposure
  metadata:
    impact: The impact of the Tugboat configuration file exposure is that DigitalOcean
      droplets may have been compromised due to the sensitive information contained
      in the file.
    recommendation: It is recommended to secure Tugboat configuration files to prevent
      any unauthorized access to DigitalOcean droplets.
requests:
- method: GET
  path:
  - '{{BaseURL}}/.tugboat'
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    words:
    - authentication
    - access_token
    - ssh_user
    condition: and
  extractors:
  - type: regex
    part: body
    regex:
    - 'access_token: .*'
