id: .idea-folder

info:
  name: Reachable or public .idea-Folder
  author: martincodes-de
  severity: info
  description: Searches for .idea-Folder by querying the /.idea endpoint
  tags: phpstorm, jetbrains, .idea, webstorm

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.idea"
      - "{{BaseURL}}/.idea/"
    matchers:
      - type: status
          status:
            - 200