id: appsettings-prod-file-disclosure

info:
  name: Application Setting Prod file disclosure
  author: tess
  severity: high
  description: |
    appsetting.json file discloses the DB connection strings containing sensitive prod information.
  metadata:
    verified: true
  tags: exposure,files

requests:
  - method: GET
    path:
      - "{{BaseURL}}/appsettings.Production.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ConnectionStrings"

      - type: word
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200
