id: amp-application-panel

info:
  name: Application Management Panel - Detect
  author: DhiyaneshDK
  severity: info
  description: Application Management Panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:cubecoders:amp:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: amp
    shodan-query: title:"AMP - Application Management Panel"
    vendor: cubecoders
    verified: true
  tags: panel,amp,cubecoders

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>AMP - Application Management Panel</title>"

      - type: word
        part: header
        words:
          - "text/html"
# digest: 490a0046304402200b41669d3e828b8e0a14fb220fff916e1a7da7eddb2419e3e1b5afa71cf42f9f022062f00ca09f59c46b4d3ff07fdeab917d543a95cea7cacec1f9592bda567a35c9:922c64590222798bb761d5b6d8e72950
