id: esphome-panel

info:
  name: ESPHome Login Panel - Detect
  author: fabaff
  severity: info
  description: ESPHome login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:esphome:esphome:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: esphome
    product: esphome
    shodan-query: title:"Login - ESPHome"
  tags: panel,esphome,iot

http:
  - method: GET
    path:
      - '{{BaseURL}}/login'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'class="esphome-header'

      - type: status
        status:
          - 200
# digest: 4b0a0048304602210080cb860fc8e46dd3992be84715c1618a768220e8cab15abcb692dece65b132e2022100ffcbf77bebd738785251911c717553827bb1c47aaf78f947b8b9a84b110ca12f:922c64590222798bb761d5b6d8e72950
