id: prometheus-exposed-panel

info:
  name: Prometheus Panel - Detect
  author: organiccrap,jfbes
  severity: info
  description: Prometheus panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 2
    vendor: prometheus
    product: prometheus
  tags: panel,prometheus

http:
  - method: GET
    path:
      - '{{BaseURL}}/graph'
      - "{{BaseURL}}/prometheus/graph"

    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - '<title>Prometheus Time Series Collection and Processing Server</title>'
# digest: 4a0a0047304502210092c8b1f9ccef94728792c4108797c913be34d7d565d247ab5ce243243461744e0220075219542f337700b0f6203b35dfd1115803d8e8e4a676cb2d4400ceb4857efd:922c64590222798bb761d5b6d8e72950