id: prometheus-exposed-panel

info:
  name: Prometheus Panel - Detect
  author: organiccrap,jfbes
  severity: info
  description: Prometheus panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: panel,prometheus

http:
  - method: GET
    path:
      - '{{BaseURL}}/graph'
      - "{{BaseURL}}/prometheus/graph"

    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - '<title>Prometheus Time Series Collection and Processing Server</title>'
# digest: 4b0a00483046022100bbe869dbee0040bc78d2063113105e46f8bdd7897e6fd9acb6ae1e399fd2e66a022100fa47844fce9a179cbaf02222a9e6acff71b2db8934cc35ea133d1a63f1e20a79:922c64590222798bb761d5b6d8e72950