id: kube-api-version

info:
  name: Kube API Version
  author: sharath
  severity: info
  description: Scans for kube version
  tags: tech,k8s,kubernetes,devops,kube

requests:
  - method: GET
    path:
      - "{{BaseURL}}/version"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "major"
          - "minor"
        condition: and