id: codeigniter-application-installer

info:
  name: Codeigniter Application Installer Exposure
  author: pussycat0x
  severity: info
  metadata:
    verified: true
    shodan-query: title:"Codeigniter Application Installer"
  tags: misconfig,condeigniter,install,exposure

requests:
  - method: GET
    path:
      - '{{BaseURL}}/install/'
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<title>Codeigniter Application Installer'

      - type: status
        status:
          - 200
