id: git-config-exposure-detect

info:
  name: git config exposure
  author: tess
  severity: medium
  metadata:
    verified: true
  tags: tech,detect,git,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"

    stop-at-first-match: true
    host-redirects: true
    max-redirects: 3
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '[core]'
          - 'remote "origin"'
          - '[branch "master"]'
        condition: and

      - type: status
        status:
          - 200
