id: misconfigured-docker
info:
  name: Docker Container - Misconfiguration Exposure
  author: dhiyaneshDK
  severity: critical
  description: The misconfigured Docker container exposes unencrypted and unauthenticated
    access to the Docker daemon via TCP.
  reference:
  - https://madhuakula.com/content/attacking-and-auditing-docker-containers-using-opensource/attacking-docker-containers/misconfiguration.html
  tags: docker,unauth,devops
  metadata:
    impact: The impact of the misconfiguration of the Docker container is that it
      exposes the Docker daemon to un-encrypted and un-authenticated requests, potentially
      leading to unauthorized access and security breaches.
    recommendation: It is highly recommended to disable tcp and enable encryption
      for Docker daemon communication to prevent misconfigurations and potential security
      breaches.
requests:
- method: GET
  path:
  - '{{BaseURL}}/images/json'
  matchers-condition: and
  matchers:
  - type: word
    words:
    - '"ParentId":'
    - '"Container":'
    - '"Labels":'
    condition: and
  - type: status
    status:
    - 200
