id: kubernetes-dockerconfigjson-secret

info:
  name: kubernetes.io/dockerconfigjson Secret
  author: dwisiswant0
  severity: info
  reference:
    - https://blog.aquasec.com/the-ticking-supply-chain-attack-bomb-of-exposed-kubernetes-secrets
  metadata:
    verified: true
  tags: kubernetes,k8s,file,keys,secret

file:
  - extensions:
      - yaml
      - yml

    extractors:
      - type: regex
        part: body
        regex:
          - \.dockerconfigjson:\s+["']?e(w|y)[\w=]+["']?
