# This is a configuration file for the bugbounty template profile.
# Additional configuration profiles can be created for different types of nuclei scans.
# They should be placed under the 'config' directory at:
# https://github.com/projectdiscovery/nuclei-templates
# Here is an example of how to use a config profile:
# nuclei -config config/bugbounty.yml -list target_list_to_scan.txt

exclude-severity:
  - info

exclude-tags:
  - tech
  - dos
  - fuzz
  - creds-stuffing
  - token-spray
  - osint

exclude-protocols:
  - ssl
  - dns
  - file
  - code
  - whois
  - workflow