id: netlify-takeover

info:
  name: netlify takeover detection
  author: 0xPrial,pdteam
  severity: high
  reference:
    - https://github.com/EdOverflow/can-i-take-over-xyz
    - https://alirazzaq.medium.com/subdomain-takeover-worth-200-ed73f0a58ffe
  tags: takeover,netlify

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Not Found - Request ID:"
          - "Not Found"
        condition: or

      - type: word
        part: header
        words:
          - "Netlify"
