id: etcd-scan

info:
  name: Etcd Scan
  author: sharath
  severity: info
  description: Scans all open urls of etcd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/version"
    matchers:
      - type: status
        status:
          - 200
  - method: GET
    path:
      - "{{BaseURL}}/v2/keys/"
    matchers:
      - type: status
        status:
          - 200
  - method: GET
    path:
      - "{{BaseURL}}/v2/keys/?recursive=true"
    matchers:
      - type: status
        status:
          - 200
  - method: GET
    path:
      - "{{BaseURL}}/v2/keys/registry/clusterrolebindings"
    matchers:
      - type: status
        status:
          - 200
  - method: GET
    path:
      - "{{BaseURL}}/v2/keys/message"
    matchers:
      - type: status
        status:
          - 200
  