id: htaccess-config

info:
  name: HTaccess config file
  author: Yash Anand @yashanand155, keni0k
  severity: info
  tags: misc,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.htaccess"
      - "{{BaseURL}}/example.htaccess"
      - "{{BaseURL}}/_.htaccess"
      - "{{BaseURL}}/sample.htaccess"
      - "{{BaseURL}}/a.htaccess"

    stop-at-first-match: true
    matchers:
      - type: word
        words:
          - RewriteRule
          - RewriteCond
          - </IfModule>
          - <IfModule
          - AddDefaultCharset
          - <FilesMatch
          - </FilesMatch>
        condition: or
