id: etcd-scan
info:
  name: Etcd Scan
  author: sharath
  severity: info
  description: Scans for etcd version
  tags: tech,k8s,kubernetes,devops,etcd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/version"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "etcdserver"