id: wp-superstorefinder-misconfig

info:
  name: Superstorefinder WP-plugin - Security Misconfigurations
  author: r3Y3r53
  severity: medium
  description: |
    Security misconfiguration is a common security issue that occurs when a system, application, or network is not properly configured to protect against threats and vulnerabilities. 
  reference:
    - https://cxsecurity.com/issue/WLB-2021010145
    - https://www.exploitalert.com/view-details.html?id=36983
  metadata:
    google-query: inurl:"wp-content/plugins/superstorefinder-wp/ssf-wp-admin/pages/exportAjax.php"
    publicwww-query: "/wp-content/plugins/superstorefinder-wp/"
    verified: true
  tags: wordpress,wp-plugin,superstorefinder-wp,wp,misconfig

http:
  - raw:
      - |
        GET /wp-content/plugins/superstorefinder-wp/ssf-wp-admin/pages/exportAjax.php HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200' 
          - 'contains(body, "Name") && contains(body, "CategoriesTags") && contains(body, "email")' 
          - 'contains(content_type, "text/html")'
        condition: and
