id: kubelet-metrics
info:
  name: Kubelet Metrics
  author: sharath
  severity: info
  description: Scans for kubelet metrics
  tags: tech,k8s,kubernetes,devops,kubelet

requests:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: regex
        part: header
        regex:
          - "text/plain"