id: manageengine-network-config

info:
  name: Zoho ManageEngine Network Configuration Manager Panel - Detect
  author: righettod
  severity: info
  description: ZOHO ManageEngine Network Configuration Manager was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:zohocorp:manageengine_network_configuration_manager:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: manageengine_network_configuration_manager
    shodan-query: http.title:"Network Configuration Manager"
    vendor: zohocorp
    verified: true
  tags: panel,zoho,manageengine,zohocorp

http:
  - method: GET
    path:
      - '{{BaseURL}}/apiclient/ember/Login.jsp'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Network Configuration Manager'
          - 'https://www.manageengine.com'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450221008f051c288f95ffdb24be18cc7304e8735c51117eb4230acb517f72a94c3c4fa9022010af7b43705349ecc297ebaa1ea88e2440932a4ac971e6c1b934706f738002dd:922c64590222798bb761d5b6d8e72950
