id: arcgis-exposed-docs

info:
  name: ArcGIS exposed docs
  author: Podalirius
  severity: info
  tags: docs,arcgis,cms

requests:
  - method: GET
    path:
      - '{{BaseURL}}/portal/portalhelp/en/'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'ArcGIS Enterprise'
          - 'Installation and Deployment'
        condition: or
        
      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '&nbsp;([0-9.]+)</span>'
