id: swagger-api-json-file

info:
  name: Public Swagger API JSON File - Detect
  author: ChrisDale
  severity: info
  description: Public Swagger API JSON file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  tags: exposure,api,swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}/api-docs/swagger.json"
      - "{{BaseURL}}/api-docs/swagger.yaml"
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/swagger.yaml"
      - "{{BaseURL}}"/openapi
      - "{{BaseURL}}/swagger/v1/swagger.json"
      - "{{BaseURL}}/swagger/v1/swagger.yaml"
      - "{{BaseURL}}/api/swagger.json"
      - "{{BaseURL}}/api/swagger.yaml"
      - "{{BaseURL}}/api/swagger.yml"
      - "{{BaseURL}}/api/api-docs/swagger.json"
      - "{{BaseURL}}/api/api-docs/swagger.yaml"
      - "{{BaseURL}}/api/swagger-ui/swagger.json"
      - "{{BaseURL}}/api/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/apidocs/swagger.json"
      - "{{BaseURL}}/api/apidocs/swagger.yaml"
      - "{{BaseURL}}/api/spec/swagger.json"
      - "{{BaseURL}}/api/spec/swagger.yaml"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.json"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/swagger_doc.json"

    headers:
      Accept: text/html
    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "paths:"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"

# digest: 4a0a00473045022100afd29a07f67f190a06a288f3e955102e590e224d636f18e6b1e02837487419bd02206bba198dbc5a7cf32d6262dd7c7ac435e0653b860795a8284fa91b621ce2ac19:922c64590222798bb761d5b6d8e72950
