name: 🛠 Template Validate

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.17

      #- name: Cache Go
      #  id: cache-go
      #  uses: actions/cache@v2
      #  with:
      #    path: /home/runner/go
      #    key: ${{ runner.os }}-go

      - name: Installing Nuclei
        # if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@master
        shell: bash

      - name: Template Validation
        run: |
          nuclei -validate -t .
      #    nuclei -validate -w ./workflows # Disabling temporarily
        shell: bash