name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'code/cves/2024/CVE-2024-3094.yaml'
    - 'http/cves/2022/CVE-2022-0424.yaml'
    - 'http/cves/2024/CVE-2024-0337.yaml'
    - 'http/cves/2024/CVE-2024-2879.yaml'
    - 'http/cves/2024/CVE-2024-3273.yaml'
    - 'http/default-logins/allnet/allnet-default-login.yaml'
    - 'http/default-logins/asus/asus-rtn16-default-login.yaml'
    - 'http/default-logins/asus/asus-wl500g-default-login.yaml'
    - 'http/default-logins/asus/asus-wl520GU-default-login.yaml'
    - 'http/exposed-panels/beyondtrust-priv-panel.yaml'
    - 'http/exposed-panels/mitel-micollab-panel.yaml'
    - 'http/exposed-panels/mitric-checker-panel.yaml'
    - 'http/exposed-panels/outsystems-servicecenter-panel.yaml'
    - 'http/exposed-panels/zenml-dashboard-panel.yaml'
    - 'http/exposures/apis/aspnet-soap-webservices-asmx.yaml'
    - 'http/misconfiguration/dlink-unauth-cgi-script.yaml'
    - 'http/misconfiguration/helm-dashboard-exposure.yaml'
    - 'http/misconfiguration/intelbras-dvr-unauth.yaml'
    - 'http/misconfiguration/thanos-prometheus-exposure.yaml'
    - 'http/technologies/citrix-xenmobile-version.yaml'
    - 'http/technologies/splunkhec-detect.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
