name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2011/CVE-2011-4640.yaml'
    - 'http/cves/2021/CVE-2021-40651.yaml'
    - 'http/cves/2023/CVE-2023-47115.yaml'
    - 'http/cves/2023/CVE-2023-6909.yaml'
    - 'http/cves/2024/CVE-2024-1061.yaml'
    - 'http/cves/2024/CVE-2024-21644.yaml'
    - 'http/cves/2024/CVE-2024-21893.yaml'
    - 'http/exposed-panels/dockge-panel.yaml'
    - 'http/exposed-panels/friendica-panel.yaml'
    - 'http/exposed-panels/ms-exchange-web-service.yaml'
    - 'http/exposed-panels/pairdrop-panel.yaml'
    - 'http/exposed-panels/passbolt-panel.yaml'
    - 'http/exposed-panels/sentry-panel.yaml'
    - 'http/miscellaneous/balada-injector-malware.yaml'
    - 'http/misconfiguration/node-express-dev-env.yaml'
    - 'http/misconfiguration/sap/sap-public-admin.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
