name: 🛠 Template Validate

on:
  pull_request:
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: nuclei install
        run: go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest

      - name: Template Validation
        run: |
          nuclei -duc -validate -allow-local-file-access -et .git -t /home/runner/work/nuclei-templates/nuclei-templates
          nuclei -duc -validate -w ./workflows -allow-local-file-access -et .git -t /home/runner/work/nuclei-templates/nuclei-templates
